require: rubocop-rspec
AllCops:
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 2.7.2
Layout/LineLength:
  Max: 100
Style/Documentation:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'